production:
  solr:
    hostname: http://ec2-west.websolr.com
    port: 8983
    path: /solr/4bb1daa014f
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING