require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlphaTestersController do

  # This should return the minimal set of attributes required to create a valid
  # AlphaTester. As you add validations to AlphaTester, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all alpha_testers as @alpha_testers" do
      alpha_tester = AlphaTester.create! valid_attributes
      get :index
      assigns(:alpha_testers).should eq([alpha_tester])
    end
  end

  describe "GET show" do
    it "assigns the requested alpha_tester as @alpha_tester" do
      alpha_tester = AlphaTester.create! valid_attributes
      get :show, :id => alpha_tester.id.to_s
      assigns(:alpha_tester).should eq(alpha_tester)
    end
  end

  describe "GET new" do
    it "assigns a new alpha_tester as @alpha_tester" do
      get :new
      assigns(:alpha_tester).should be_a_new(AlphaTester)
    end
  end

  describe "GET edit" do
    it "assigns the requested alpha_tester as @alpha_tester" do
      alpha_tester = AlphaTester.create! valid_attributes
      get :edit, :id => alpha_tester.id.to_s
      assigns(:alpha_tester).should eq(alpha_tester)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlphaTester" do
        expect {
          post :create, :alpha_tester => valid_attributes
        }.to change(AlphaTester, :count).by(1)
      end

      it "assigns a newly created alpha_tester as @alpha_tester" do
        post :create, :alpha_tester => valid_attributes
        assigns(:alpha_tester).should be_a(AlphaTester)
        assigns(:alpha_tester).should be_persisted
      end

      it "redirects to the created alpha_tester" do
        post :create, :alpha_tester => valid_attributes
        response.should redirect_to(AlphaTester.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alpha_tester as @alpha_tester" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlphaTester.any_instance.stub(:save).and_return(false)
        post :create, :alpha_tester => {}
        assigns(:alpha_tester).should be_a_new(AlphaTester)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlphaTester.any_instance.stub(:save).and_return(false)
        post :create, :alpha_tester => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested alpha_tester" do
        alpha_tester = AlphaTester.create! valid_attributes
        # Assuming there are no other alpha_testers in the database, this
        # specifies that the AlphaTester created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AlphaTester.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => alpha_tester.id, :alpha_tester => {'these' => 'params'}
      end

      it "assigns the requested alpha_tester as @alpha_tester" do
        alpha_tester = AlphaTester.create! valid_attributes
        put :update, :id => alpha_tester.id, :alpha_tester => valid_attributes
        assigns(:alpha_tester).should eq(alpha_tester)
      end

      it "redirects to the alpha_tester" do
        alpha_tester = AlphaTester.create! valid_attributes
        put :update, :id => alpha_tester.id, :alpha_tester => valid_attributes
        response.should redirect_to(alpha_tester)
      end
    end

    describe "with invalid params" do
      it "assigns the alpha_tester as @alpha_tester" do
        alpha_tester = AlphaTester.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlphaTester.any_instance.stub(:save).and_return(false)
        put :update, :id => alpha_tester.id.to_s, :alpha_tester => {}
        assigns(:alpha_tester).should eq(alpha_tester)
      end

      it "re-renders the 'edit' template" do
        alpha_tester = AlphaTester.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlphaTester.any_instance.stub(:save).and_return(false)
        put :update, :id => alpha_tester.id.to_s, :alpha_tester => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alpha_tester" do
      alpha_tester = AlphaTester.create! valid_attributes
      expect {
        delete :destroy, :id => alpha_tester.id.to_s
      }.to change(AlphaTester, :count).by(-1)
    end

    it "redirects to the alpha_testers list" do
      alpha_tester = AlphaTester.create! valid_attributes
      delete :destroy, :id => alpha_tester.id.to_s
      response.should redirect_to(alpha_testers_url)
    end
  end

end
