require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FoursquareCheckinsController do

  # This should return the minimal set of attributes required to create a valid
  # FoursquareCheckin. As you add validations to FoursquareCheckin, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all foursquare_checkins as @foursquare_checkins" do
      foursquare_checkin = FoursquareCheckin.create! valid_attributes
      get :index
      assigns(:foursquare_checkins).should eq([foursquare_checkin])
    end
  end

  describe "GET show" do
    it "assigns the requested foursquare_checkin as @foursquare_checkin" do
      foursquare_checkin = FoursquareCheckin.create! valid_attributes
      get :show, :id => foursquare_checkin.id.to_s
      assigns(:foursquare_checkin).should eq(foursquare_checkin)
    end
  end

  describe "GET new" do
    it "assigns a new foursquare_checkin as @foursquare_checkin" do
      get :new
      assigns(:foursquare_checkin).should be_a_new(FoursquareCheckin)
    end
  end

  describe "GET edit" do
    it "assigns the requested foursquare_checkin as @foursquare_checkin" do
      foursquare_checkin = FoursquareCheckin.create! valid_attributes
      get :edit, :id => foursquare_checkin.id.to_s
      assigns(:foursquare_checkin).should eq(foursquare_checkin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FoursquareCheckin" do
        expect {
          post :create, :foursquare_checkin => valid_attributes
        }.to change(FoursquareCheckin, :count).by(1)
      end

      it "assigns a newly created foursquare_checkin as @foursquare_checkin" do
        post :create, :foursquare_checkin => valid_attributes
        assigns(:foursquare_checkin).should be_a(FoursquareCheckin)
        assigns(:foursquare_checkin).should be_persisted
      end

      it "redirects to the created foursquare_checkin" do
        post :create, :foursquare_checkin => valid_attributes
        response.should redirect_to(FoursquareCheckin.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved foursquare_checkin as @foursquare_checkin" do
        # Trigger the behavior that occurs when invalid params are submitted
        FoursquareCheckin.any_instance.stub(:save).and_return(false)
        post :create, :foursquare_checkin => {}
        assigns(:foursquare_checkin).should be_a_new(FoursquareCheckin)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FoursquareCheckin.any_instance.stub(:save).and_return(false)
        post :create, :foursquare_checkin => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested foursquare_checkin" do
        foursquare_checkin = FoursquareCheckin.create! valid_attributes
        # Assuming there are no other foursquare_checkins in the database, this
        # specifies that the FoursquareCheckin created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FoursquareCheckin.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => foursquare_checkin.id, :foursquare_checkin => {'these' => 'params'}
      end

      it "assigns the requested foursquare_checkin as @foursquare_checkin" do
        foursquare_checkin = FoursquareCheckin.create! valid_attributes
        put :update, :id => foursquare_checkin.id, :foursquare_checkin => valid_attributes
        assigns(:foursquare_checkin).should eq(foursquare_checkin)
      end

      it "redirects to the foursquare_checkin" do
        foursquare_checkin = FoursquareCheckin.create! valid_attributes
        put :update, :id => foursquare_checkin.id, :foursquare_checkin => valid_attributes
        response.should redirect_to(foursquare_checkin)
      end
    end

    describe "with invalid params" do
      it "assigns the foursquare_checkin as @foursquare_checkin" do
        foursquare_checkin = FoursquareCheckin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FoursquareCheckin.any_instance.stub(:save).and_return(false)
        put :update, :id => foursquare_checkin.id.to_s, :foursquare_checkin => {}
        assigns(:foursquare_checkin).should eq(foursquare_checkin)
      end

      it "re-renders the 'edit' template" do
        foursquare_checkin = FoursquareCheckin.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FoursquareCheckin.any_instance.stub(:save).and_return(false)
        put :update, :id => foursquare_checkin.id.to_s, :foursquare_checkin => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested foursquare_checkin" do
      foursquare_checkin = FoursquareCheckin.create! valid_attributes
      expect {
        delete :destroy, :id => foursquare_checkin.id.to_s
      }.to change(FoursquareCheckin, :count).by(-1)
    end

    it "redirects to the foursquare_checkins list" do
      foursquare_checkin = FoursquareCheckin.create! valid_attributes
      delete :destroy, :id => foursquare_checkin.id.to_s
      response.should redirect_to(foursquare_checkins_url)
    end
  end

end
