require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MenuItemRatingsController do

  def mock_menu_item_rating(stubs={})
    @mock_menu_item_rating ||= mock_model(MenuItemRating, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all menu_item_ratings as @menu_item_ratings" do
      MenuItemRating.stub(:all) { [mock_menu_item_rating] }
      get :index
      assigns(:menu_item_ratings).should eq([mock_menu_item_rating])
    end
  end

  describe "GET show" do
    it "assigns the requested menu_item_rating as @menu_item_rating" do
      MenuItemRating.stub(:find).with("37") { mock_menu_item_rating }
      get :show, :id => "37"
      assigns(:menu_item_rating).should be(mock_menu_item_rating)
    end
  end

  describe "GET new" do
    it "assigns a new menu_item_rating as @menu_item_rating" do
      MenuItemRating.stub(:new) { mock_menu_item_rating }
      get :new
      assigns(:menu_item_rating).should be(mock_menu_item_rating)
    end
  end

  describe "GET edit" do
    it "assigns the requested menu_item_rating as @menu_item_rating" do
      MenuItemRating.stub(:find).with("37") { mock_menu_item_rating }
      get :edit, :id => "37"
      assigns(:menu_item_rating).should be(mock_menu_item_rating)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created menu_item_rating as @menu_item_rating" do
        MenuItemRating.stub(:new).with({'these' => 'params'}) { mock_menu_item_rating(:save => true) }
        post :create, :menu_item_rating => {'these' => 'params'}
        assigns(:menu_item_rating).should be(mock_menu_item_rating)
      end

      it "redirects to the created menu_item_rating" do
        MenuItemRating.stub(:new) { mock_menu_item_rating(:save => true) }
        post :create, :menu_item_rating => {}
        response.should redirect_to(menu_item_rating_url(mock_menu_item_rating))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved menu_item_rating as @menu_item_rating" do
        MenuItemRating.stub(:new).with({'these' => 'params'}) { mock_menu_item_rating(:save => false) }
        post :create, :menu_item_rating => {'these' => 'params'}
        assigns(:menu_item_rating).should be(mock_menu_item_rating)
      end

      it "re-renders the 'new' template" do
        MenuItemRating.stub(:new) { mock_menu_item_rating(:save => false) }
        post :create, :menu_item_rating => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested menu_item_rating" do
        MenuItemRating.stub(:find).with("37") { mock_menu_item_rating }
        mock_menu_item_rating.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :menu_item_rating => {'these' => 'params'}
      end

      it "assigns the requested menu_item_rating as @menu_item_rating" do
        MenuItemRating.stub(:find) { mock_menu_item_rating(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:menu_item_rating).should be(mock_menu_item_rating)
      end

      it "redirects to the menu_item_rating" do
        MenuItemRating.stub(:find) { mock_menu_item_rating(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(menu_item_rating_url(mock_menu_item_rating))
      end
    end

    describe "with invalid params" do
      it "assigns the menu_item_rating as @menu_item_rating" do
        MenuItemRating.stub(:find) { mock_menu_item_rating(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:menu_item_rating).should be(mock_menu_item_rating)
      end

      it "re-renders the 'edit' template" do
        MenuItemRating.stub(:find) { mock_menu_item_rating(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested menu_item_rating" do
      MenuItemRating.stub(:find).with("37") { mock_menu_item_rating }
      mock_menu_item_rating.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the menu_item_ratings list" do
      MenuItemRating.stub(:find) { mock_menu_item_rating }
      delete :destroy, :id => "1"
      response.should redirect_to(menu_item_ratings_url)
    end
  end

end
