require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MenuLabelAssociationsController do

  def mock_menu_label_association(stubs={})
    @mock_menu_label_association ||= mock_model(MenuLabelAssociation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all menu_label_associations as @menu_label_associations" do
      MenuLabelAssociation.stub(:all) { [mock_menu_label_association] }
      get :index
      assigns(:menu_label_associations).should eq([mock_menu_label_association])
    end
  end

  describe "GET show" do
    it "assigns the requested menu_label_association as @menu_label_association" do
      MenuLabelAssociation.stub(:find).with("37") { mock_menu_label_association }
      get :show, :id => "37"
      assigns(:menu_label_association).should be(mock_menu_label_association)
    end
  end

  describe "GET new" do
    it "assigns a new menu_label_association as @menu_label_association" do
      MenuLabelAssociation.stub(:new) { mock_menu_label_association }
      get :new
      assigns(:menu_label_association).should be(mock_menu_label_association)
    end
  end

  describe "GET edit" do
    it "assigns the requested menu_label_association as @menu_label_association" do
      MenuLabelAssociation.stub(:find).with("37") { mock_menu_label_association }
      get :edit, :id => "37"
      assigns(:menu_label_association).should be(mock_menu_label_association)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created menu_label_association as @menu_label_association" do
        MenuLabelAssociation.stub(:new).with({'these' => 'params'}) { mock_menu_label_association(:save => true) }
        post :create, :menu_label_association => {'these' => 'params'}
        assigns(:menu_label_association).should be(mock_menu_label_association)
      end

      it "redirects to the created menu_label_association" do
        MenuLabelAssociation.stub(:new) { mock_menu_label_association(:save => true) }
        post :create, :menu_label_association => {}
        response.should redirect_to(menu_label_association_url(mock_menu_label_association))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved menu_label_association as @menu_label_association" do
        MenuLabelAssociation.stub(:new).with({'these' => 'params'}) { mock_menu_label_association(:save => false) }
        post :create, :menu_label_association => {'these' => 'params'}
        assigns(:menu_label_association).should be(mock_menu_label_association)
      end

      it "re-renders the 'new' template" do
        MenuLabelAssociation.stub(:new) { mock_menu_label_association(:save => false) }
        post :create, :menu_label_association => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested menu_label_association" do
        MenuLabelAssociation.stub(:find).with("37") { mock_menu_label_association }
        mock_menu_label_association.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :menu_label_association => {'these' => 'params'}
      end

      it "assigns the requested menu_label_association as @menu_label_association" do
        MenuLabelAssociation.stub(:find) { mock_menu_label_association(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:menu_label_association).should be(mock_menu_label_association)
      end

      it "redirects to the menu_label_association" do
        MenuLabelAssociation.stub(:find) { mock_menu_label_association(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(menu_label_association_url(mock_menu_label_association))
      end
    end

    describe "with invalid params" do
      it "assigns the menu_label_association as @menu_label_association" do
        MenuLabelAssociation.stub(:find) { mock_menu_label_association(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:menu_label_association).should be(mock_menu_label_association)
      end

      it "re-renders the 'edit' template" do
        MenuLabelAssociation.stub(:find) { mock_menu_label_association(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested menu_label_association" do
      MenuLabelAssociation.stub(:find).with("37") { mock_menu_label_association }
      mock_menu_label_association.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the menu_label_associations list" do
      MenuLabelAssociation.stub(:find) { mock_menu_label_association }
      delete :destroy, :id => "1"
      response.should redirect_to(menu_label_associations_url)
    end
  end

end
