require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MenuLabelsController do

  def mock_menu_label(stubs={})
    @mock_menu_label ||= mock_model(MenuLabel, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all menu_labels as @menu_labels" do
      MenuLabel.stub(:all) { [mock_menu_label] }
      get :index
      assigns(:menu_labels).should eq([mock_menu_label])
    end
  end

  describe "GET show" do
    it "assigns the requested menu_label as @menu_label" do
      MenuLabel.stub(:find).with("37") { mock_menu_label }
      get :show, :id => "37"
      assigns(:menu_label).should be(mock_menu_label)
    end
  end

  describe "GET new" do
    it "assigns a new menu_label as @menu_label" do
      MenuLabel.stub(:new) { mock_menu_label }
      get :new
      assigns(:menu_label).should be(mock_menu_label)
    end
  end

  describe "GET edit" do
    it "assigns the requested menu_label as @menu_label" do
      MenuLabel.stub(:find).with("37") { mock_menu_label }
      get :edit, :id => "37"
      assigns(:menu_label).should be(mock_menu_label)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created menu_label as @menu_label" do
        MenuLabel.stub(:new).with({'these' => 'params'}) { mock_menu_label(:save => true) }
        post :create, :menu_label => {'these' => 'params'}
        assigns(:menu_label).should be(mock_menu_label)
      end

      it "redirects to the created menu_label" do
        MenuLabel.stub(:new) { mock_menu_label(:save => true) }
        post :create, :menu_label => {}
        response.should redirect_to(menu_label_url(mock_menu_label))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved menu_label as @menu_label" do
        MenuLabel.stub(:new).with({'these' => 'params'}) { mock_menu_label(:save => false) }
        post :create, :menu_label => {'these' => 'params'}
        assigns(:menu_label).should be(mock_menu_label)
      end

      it "re-renders the 'new' template" do
        MenuLabel.stub(:new) { mock_menu_label(:save => false) }
        post :create, :menu_label => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested menu_label" do
        MenuLabel.stub(:find).with("37") { mock_menu_label }
        mock_menu_label.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :menu_label => {'these' => 'params'}
      end

      it "assigns the requested menu_label as @menu_label" do
        MenuLabel.stub(:find) { mock_menu_label(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:menu_label).should be(mock_menu_label)
      end

      it "redirects to the menu_label" do
        MenuLabel.stub(:find) { mock_menu_label(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(menu_label_url(mock_menu_label))
      end
    end

    describe "with invalid params" do
      it "assigns the menu_label as @menu_label" do
        MenuLabel.stub(:find) { mock_menu_label(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:menu_label).should be(mock_menu_label)
      end

      it "re-renders the 'edit' template" do
        MenuLabel.stub(:find) { mock_menu_label(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested menu_label" do
      MenuLabel.stub(:find).with("37") { mock_menu_label }
      mock_menu_label.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the menu_labels list" do
      MenuLabel.stub(:find) { mock_menu_label }
      delete :destroy, :id => "1"
      response.should redirect_to(menu_labels_url)
    end
  end

end
