require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MenuItemPhotosController do

  def mock_menu_item_photo(stubs={})
    @mock_menu_item_photo ||= mock_model(MenuItemPhoto, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all menu_item_photos as @menu_item_photos" do
      MenuItemPhoto.stub(:all) { [mock_menu_item_photo] }
      get :index
      assigns(:menu_item_photos).should eq([mock_menu_item_photo])
    end
  end

  describe "GET show" do
    it "assigns the requested menu_item_photo as @menu_item_photo" do
      MenuItemPhoto.stub(:find).with("37") { mock_menu_item_photo }
      get :show, :id => "37"
      assigns(:menu_item_photo).should be(mock_menu_item_photo)
    end
  end

  describe "GET new" do
    it "assigns a new menu_item_photo as @menu_item_photo" do
      MenuItemPhoto.stub(:new) { mock_menu_item_photo }
      get :new
      assigns(:menu_item_photo).should be(mock_menu_item_photo)
    end
  end

  describe "GET edit" do
    it "assigns the requested menu_item_photo as @menu_item_photo" do
      MenuItemPhoto.stub(:find).with("37") { mock_menu_item_photo }
      get :edit, :id => "37"
      assigns(:menu_item_photo).should be(mock_menu_item_photo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created menu_item_photo as @menu_item_photo" do
        MenuItemPhoto.stub(:new).with({'these' => 'params'}) { mock_menu_item_photo(:save => true) }
        post :create, :menu_item_photo => {'these' => 'params'}
        assigns(:menu_item_photo).should be(mock_menu_item_photo)
      end

      it "redirects to the created menu_item_photo" do
        MenuItemPhoto.stub(:new) { mock_menu_item_photo(:save => true) }
        post :create, :menu_item_photo => {}
        response.should redirect_to(menu_item_photo_url(mock_menu_item_photo))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved menu_item_photo as @menu_item_photo" do
        MenuItemPhoto.stub(:new).with({'these' => 'params'}) { mock_menu_item_photo(:save => false) }
        post :create, :menu_item_photo => {'these' => 'params'}
        assigns(:menu_item_photo).should be(mock_menu_item_photo)
      end

      it "re-renders the 'new' template" do
        MenuItemPhoto.stub(:new) { mock_menu_item_photo(:save => false) }
        post :create, :menu_item_photo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested menu_item_photo" do
        MenuItemPhoto.stub(:find).with("37") { mock_menu_item_photo }
        mock_menu_item_photo.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :menu_item_photo => {'these' => 'params'}
      end

      it "assigns the requested menu_item_photo as @menu_item_photo" do
        MenuItemPhoto.stub(:find) { mock_menu_item_photo(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:menu_item_photo).should be(mock_menu_item_photo)
      end

      it "redirects to the menu_item_photo" do
        MenuItemPhoto.stub(:find) { mock_menu_item_photo(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(menu_item_photo_url(mock_menu_item_photo))
      end
    end

    describe "with invalid params" do
      it "assigns the menu_item_photo as @menu_item_photo" do
        MenuItemPhoto.stub(:find) { mock_menu_item_photo(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:menu_item_photo).should be(mock_menu_item_photo)
      end

      it "re-renders the 'edit' template" do
        MenuItemPhoto.stub(:find) { mock_menu_item_photo(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested menu_item_photo" do
      MenuItemPhoto.stub(:find).with("37") { mock_menu_item_photo }
      mock_menu_item_photo.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the menu_item_photos list" do
      MenuItemPhoto.stub(:find) { mock_menu_item_photo }
      delete :destroy, :id => "1"
      response.should redirect_to(menu_item_photos_url)
    end
  end

end
