require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MenuItemRatingHelpfulsController do

  def mock_menu_item_rating_helpful(stubs={})
    @mock_menu_item_rating_helpful ||= mock_model(MenuItemRatingHelpful, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all menu_item_rating_helpfuls as @menu_item_rating_helpfuls" do
      MenuItemRatingHelpful.stub(:all) { [mock_menu_item_rating_helpful] }
      get :index
      assigns(:menu_item_rating_helpfuls).should eq([mock_menu_item_rating_helpful])
    end
  end

  describe "GET show" do
    it "assigns the requested menu_item_rating_helpful as @menu_item_rating_helpful" do
      MenuItemRatingHelpful.stub(:find).with("37") { mock_menu_item_rating_helpful }
      get :show, :id => "37"
      assigns(:menu_item_rating_helpful).should be(mock_menu_item_rating_helpful)
    end
  end

  describe "GET new" do
    it "assigns a new menu_item_rating_helpful as @menu_item_rating_helpful" do
      MenuItemRatingHelpful.stub(:new) { mock_menu_item_rating_helpful }
      get :new
      assigns(:menu_item_rating_helpful).should be(mock_menu_item_rating_helpful)
    end
  end

  describe "GET edit" do
    it "assigns the requested menu_item_rating_helpful as @menu_item_rating_helpful" do
      MenuItemRatingHelpful.stub(:find).with("37") { mock_menu_item_rating_helpful }
      get :edit, :id => "37"
      assigns(:menu_item_rating_helpful).should be(mock_menu_item_rating_helpful)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created menu_item_rating_helpful as @menu_item_rating_helpful" do
        MenuItemRatingHelpful.stub(:new).with({'these' => 'params'}) { mock_menu_item_rating_helpful(:save => true) }
        post :create, :menu_item_rating_helpful => {'these' => 'params'}
        assigns(:menu_item_rating_helpful).should be(mock_menu_item_rating_helpful)
      end

      it "redirects to the created menu_item_rating_helpful" do
        MenuItemRatingHelpful.stub(:new) { mock_menu_item_rating_helpful(:save => true) }
        post :create, :menu_item_rating_helpful => {}
        response.should redirect_to(menu_item_rating_helpful_url(mock_menu_item_rating_helpful))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved menu_item_rating_helpful as @menu_item_rating_helpful" do
        MenuItemRatingHelpful.stub(:new).with({'these' => 'params'}) { mock_menu_item_rating_helpful(:save => false) }
        post :create, :menu_item_rating_helpful => {'these' => 'params'}
        assigns(:menu_item_rating_helpful).should be(mock_menu_item_rating_helpful)
      end

      it "re-renders the 'new' template" do
        MenuItemRatingHelpful.stub(:new) { mock_menu_item_rating_helpful(:save => false) }
        post :create, :menu_item_rating_helpful => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested menu_item_rating_helpful" do
        MenuItemRatingHelpful.stub(:find).with("37") { mock_menu_item_rating_helpful }
        mock_menu_item_rating_helpful.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :menu_item_rating_helpful => {'these' => 'params'}
      end

      it "assigns the requested menu_item_rating_helpful as @menu_item_rating_helpful" do
        MenuItemRatingHelpful.stub(:find) { mock_menu_item_rating_helpful(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:menu_item_rating_helpful).should be(mock_menu_item_rating_helpful)
      end

      it "redirects to the menu_item_rating_helpful" do
        MenuItemRatingHelpful.stub(:find) { mock_menu_item_rating_helpful(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(menu_item_rating_helpful_url(mock_menu_item_rating_helpful))
      end
    end

    describe "with invalid params" do
      it "assigns the menu_item_rating_helpful as @menu_item_rating_helpful" do
        MenuItemRatingHelpful.stub(:find) { mock_menu_item_rating_helpful(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:menu_item_rating_helpful).should be(mock_menu_item_rating_helpful)
      end

      it "re-renders the 'edit' template" do
        MenuItemRatingHelpful.stub(:find) { mock_menu_item_rating_helpful(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested menu_item_rating_helpful" do
      MenuItemRatingHelpful.stub(:find).with("37") { mock_menu_item_rating_helpful }
      mock_menu_item_rating_helpful.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the menu_item_rating_helpfuls list" do
      MenuItemRatingHelpful.stub(:find) { mock_menu_item_rating_helpful }
      delete :destroy, :id => "1"
      response.should redirect_to(menu_item_rating_helpfuls_url)
    end
  end

end
