require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MenuItemPricesController do

  def mock_menu_item_price(stubs={})
    @mock_menu_item_price ||= mock_model(MenuItemPrice, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all menu_item_prices as @menu_item_prices" do
      MenuItemPrice.stub(:all) { [mock_menu_item_price] }
      get :index
      assigns(:menu_item_prices).should eq([mock_menu_item_price])
    end
  end

  describe "GET show" do
    it "assigns the requested menu_item_price as @menu_item_price" do
      MenuItemPrice.stub(:find).with("37") { mock_menu_item_price }
      get :show, :id => "37"
      assigns(:menu_item_price).should be(mock_menu_item_price)
    end
  end

  describe "GET new" do
    it "assigns a new menu_item_price as @menu_item_price" do
      MenuItemPrice.stub(:new) { mock_menu_item_price }
      get :new
      assigns(:menu_item_price).should be(mock_menu_item_price)
    end
  end

  describe "GET edit" do
    it "assigns the requested menu_item_price as @menu_item_price" do
      MenuItemPrice.stub(:find).with("37") { mock_menu_item_price }
      get :edit, :id => "37"
      assigns(:menu_item_price).should be(mock_menu_item_price)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created menu_item_price as @menu_item_price" do
        MenuItemPrice.stub(:new).with({'these' => 'params'}) { mock_menu_item_price(:save => true) }
        post :create, :menu_item_price => {'these' => 'params'}
        assigns(:menu_item_price).should be(mock_menu_item_price)
      end

      it "redirects to the created menu_item_price" do
        MenuItemPrice.stub(:new) { mock_menu_item_price(:save => true) }
        post :create, :menu_item_price => {}
        response.should redirect_to(menu_item_price_url(mock_menu_item_price))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved menu_item_price as @menu_item_price" do
        MenuItemPrice.stub(:new).with({'these' => 'params'}) { mock_menu_item_price(:save => false) }
        post :create, :menu_item_price => {'these' => 'params'}
        assigns(:menu_item_price).should be(mock_menu_item_price)
      end

      it "re-renders the 'new' template" do
        MenuItemPrice.stub(:new) { mock_menu_item_price(:save => false) }
        post :create, :menu_item_price => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested menu_item_price" do
        MenuItemPrice.stub(:find).with("37") { mock_menu_item_price }
        mock_menu_item_price.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :menu_item_price => {'these' => 'params'}
      end

      it "assigns the requested menu_item_price as @menu_item_price" do
        MenuItemPrice.stub(:find) { mock_menu_item_price(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:menu_item_price).should be(mock_menu_item_price)
      end

      it "redirects to the menu_item_price" do
        MenuItemPrice.stub(:find) { mock_menu_item_price(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(menu_item_price_url(mock_menu_item_price))
      end
    end

    describe "with invalid params" do
      it "assigns the menu_item_price as @menu_item_price" do
        MenuItemPrice.stub(:find) { mock_menu_item_price(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:menu_item_price).should be(mock_menu_item_price)
      end

      it "re-renders the 'edit' template" do
        MenuItemPrice.stub(:find) { mock_menu_item_price(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested menu_item_price" do
      MenuItemPrice.stub(:find).with("37") { mock_menu_item_price }
      mock_menu_item_price.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the menu_item_prices list" do
      MenuItemPrice.stub(:find) { mock_menu_item_price }
      delete :destroy, :id => "1"
      response.should redirect_to(menu_item_prices_url)
    end
  end

end
