require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RestaurantLabelAssociationsController do

  def mock_restaurant_label_association(stubs={})
    @mock_restaurant_label_association ||= mock_model(RestaurantLabelAssociation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all restaurant_label_associations as @restaurant_label_associations" do
      RestaurantLabelAssociation.stub(:all) { [mock_restaurant_label_association] }
      get :index
      assigns(:restaurant_label_associations).should eq([mock_restaurant_label_association])
    end
  end

  describe "GET show" do
    it "assigns the requested restaurant_label_association as @restaurant_label_association" do
      RestaurantLabelAssociation.stub(:find).with("37") { mock_restaurant_label_association }
      get :show, :id => "37"
      assigns(:restaurant_label_association).should be(mock_restaurant_label_association)
    end
  end

  describe "GET new" do
    it "assigns a new restaurant_label_association as @restaurant_label_association" do
      RestaurantLabelAssociation.stub(:new) { mock_restaurant_label_association }
      get :new
      assigns(:restaurant_label_association).should be(mock_restaurant_label_association)
    end
  end

  describe "GET edit" do
    it "assigns the requested restaurant_label_association as @restaurant_label_association" do
      RestaurantLabelAssociation.stub(:find).with("37") { mock_restaurant_label_association }
      get :edit, :id => "37"
      assigns(:restaurant_label_association).should be(mock_restaurant_label_association)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created restaurant_label_association as @restaurant_label_association" do
        RestaurantLabelAssociation.stub(:new).with({'these' => 'params'}) { mock_restaurant_label_association(:save => true) }
        post :create, :restaurant_label_association => {'these' => 'params'}
        assigns(:restaurant_label_association).should be(mock_restaurant_label_association)
      end

      it "redirects to the created restaurant_label_association" do
        RestaurantLabelAssociation.stub(:new) { mock_restaurant_label_association(:save => true) }
        post :create, :restaurant_label_association => {}
        response.should redirect_to(restaurant_label_association_url(mock_restaurant_label_association))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved restaurant_label_association as @restaurant_label_association" do
        RestaurantLabelAssociation.stub(:new).with({'these' => 'params'}) { mock_restaurant_label_association(:save => false) }
        post :create, :restaurant_label_association => {'these' => 'params'}
        assigns(:restaurant_label_association).should be(mock_restaurant_label_association)
      end

      it "re-renders the 'new' template" do
        RestaurantLabelAssociation.stub(:new) { mock_restaurant_label_association(:save => false) }
        post :create, :restaurant_label_association => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested restaurant_label_association" do
        RestaurantLabelAssociation.stub(:find).with("37") { mock_restaurant_label_association }
        mock_restaurant_label_association.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :restaurant_label_association => {'these' => 'params'}
      end

      it "assigns the requested restaurant_label_association as @restaurant_label_association" do
        RestaurantLabelAssociation.stub(:find) { mock_restaurant_label_association(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:restaurant_label_association).should be(mock_restaurant_label_association)
      end

      it "redirects to the restaurant_label_association" do
        RestaurantLabelAssociation.stub(:find) { mock_restaurant_label_association(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(restaurant_label_association_url(mock_restaurant_label_association))
      end
    end

    describe "with invalid params" do
      it "assigns the restaurant_label_association as @restaurant_label_association" do
        RestaurantLabelAssociation.stub(:find) { mock_restaurant_label_association(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:restaurant_label_association).should be(mock_restaurant_label_association)
      end

      it "re-renders the 'edit' template" do
        RestaurantLabelAssociation.stub(:find) { mock_restaurant_label_association(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested restaurant_label_association" do
      RestaurantLabelAssociation.stub(:find).with("37") { mock_restaurant_label_association }
      mock_restaurant_label_association.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the restaurant_label_associations list" do
      RestaurantLabelAssociation.stub(:find) { mock_restaurant_label_association }
      delete :destroy, :id => "1"
      response.should redirect_to(restaurant_label_associations_url)
    end
  end

end
