require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RestaurantCuisinesController do

  def mock_restaurant_cuisine(stubs={})
    @mock_restaurant_cuisine ||= mock_model(RestaurantCuisine, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all restaurant_cuisines as @restaurant_cuisines" do
      RestaurantCuisine.stub(:all) { [mock_restaurant_cuisine] }
      get :index
      assigns(:restaurant_cuisines).should eq([mock_restaurant_cuisine])
    end
  end

  describe "GET show" do
    it "assigns the requested restaurant_cuisine as @restaurant_cuisine" do
      RestaurantCuisine.stub(:find).with("37") { mock_restaurant_cuisine }
      get :show, :id => "37"
      assigns(:restaurant_cuisine).should be(mock_restaurant_cuisine)
    end
  end

  describe "GET new" do
    it "assigns a new restaurant_cuisine as @restaurant_cuisine" do
      RestaurantCuisine.stub(:new) { mock_restaurant_cuisine }
      get :new
      assigns(:restaurant_cuisine).should be(mock_restaurant_cuisine)
    end
  end

  describe "GET edit" do
    it "assigns the requested restaurant_cuisine as @restaurant_cuisine" do
      RestaurantCuisine.stub(:find).with("37") { mock_restaurant_cuisine }
      get :edit, :id => "37"
      assigns(:restaurant_cuisine).should be(mock_restaurant_cuisine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created restaurant_cuisine as @restaurant_cuisine" do
        RestaurantCuisine.stub(:new).with({'these' => 'params'}) { mock_restaurant_cuisine(:save => true) }
        post :create, :restaurant_cuisine => {'these' => 'params'}
        assigns(:restaurant_cuisine).should be(mock_restaurant_cuisine)
      end

      it "redirects to the created restaurant_cuisine" do
        RestaurantCuisine.stub(:new) { mock_restaurant_cuisine(:save => true) }
        post :create, :restaurant_cuisine => {}
        response.should redirect_to(restaurant_cuisine_url(mock_restaurant_cuisine))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved restaurant_cuisine as @restaurant_cuisine" do
        RestaurantCuisine.stub(:new).with({'these' => 'params'}) { mock_restaurant_cuisine(:save => false) }
        post :create, :restaurant_cuisine => {'these' => 'params'}
        assigns(:restaurant_cuisine).should be(mock_restaurant_cuisine)
      end

      it "re-renders the 'new' template" do
        RestaurantCuisine.stub(:new) { mock_restaurant_cuisine(:save => false) }
        post :create, :restaurant_cuisine => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested restaurant_cuisine" do
        RestaurantCuisine.stub(:find).with("37") { mock_restaurant_cuisine }
        mock_restaurant_cuisine.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :restaurant_cuisine => {'these' => 'params'}
      end

      it "assigns the requested restaurant_cuisine as @restaurant_cuisine" do
        RestaurantCuisine.stub(:find) { mock_restaurant_cuisine(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:restaurant_cuisine).should be(mock_restaurant_cuisine)
      end

      it "redirects to the restaurant_cuisine" do
        RestaurantCuisine.stub(:find) { mock_restaurant_cuisine(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(restaurant_cuisine_url(mock_restaurant_cuisine))
      end
    end

    describe "with invalid params" do
      it "assigns the restaurant_cuisine as @restaurant_cuisine" do
        RestaurantCuisine.stub(:find) { mock_restaurant_cuisine(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:restaurant_cuisine).should be(mock_restaurant_cuisine)
      end

      it "re-renders the 'edit' template" do
        RestaurantCuisine.stub(:find) { mock_restaurant_cuisine(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested restaurant_cuisine" do
      RestaurantCuisine.stub(:find).with("37") { mock_restaurant_cuisine }
      mock_restaurant_cuisine.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the restaurant_cuisines list" do
      RestaurantCuisine.stub(:find) { mock_restaurant_cuisine }
      delete :destroy, :id => "1"
      response.should redirect_to(restaurant_cuisines_url)
    end
  end

end
