require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UserSavedMenuItemsController do

  def mock_user_saved_menu_item(stubs={})
    @mock_user_saved_menu_item ||= mock_model(UserSavedMenuItem, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all user_saved_menu_items as @user_saved_menu_items" do
      UserSavedMenuItem.stub(:all) { [mock_user_saved_menu_item] }
      get :index
      assigns(:user_saved_menu_items).should eq([mock_user_saved_menu_item])
    end
  end

  describe "GET show" do
    it "assigns the requested user_saved_menu_item as @user_saved_menu_item" do
      UserSavedMenuItem.stub(:find).with("37") { mock_user_saved_menu_item }
      get :show, :id => "37"
      assigns(:user_saved_menu_item).should be(mock_user_saved_menu_item)
    end
  end

  describe "GET new" do
    it "assigns a new user_saved_menu_item as @user_saved_menu_item" do
      UserSavedMenuItem.stub(:new) { mock_user_saved_menu_item }
      get :new
      assigns(:user_saved_menu_item).should be(mock_user_saved_menu_item)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_saved_menu_item as @user_saved_menu_item" do
      UserSavedMenuItem.stub(:find).with("37") { mock_user_saved_menu_item }
      get :edit, :id => "37"
      assigns(:user_saved_menu_item).should be(mock_user_saved_menu_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created user_saved_menu_item as @user_saved_menu_item" do
        UserSavedMenuItem.stub(:new).with({'these' => 'params'}) { mock_user_saved_menu_item(:save => true) }
        post :create, :user_saved_menu_item => {'these' => 'params'}
        assigns(:user_saved_menu_item).should be(mock_user_saved_menu_item)
      end

      it "redirects to the created user_saved_menu_item" do
        UserSavedMenuItem.stub(:new) { mock_user_saved_menu_item(:save => true) }
        post :create, :user_saved_menu_item => {}
        response.should redirect_to(user_saved_menu_item_url(mock_user_saved_menu_item))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_saved_menu_item as @user_saved_menu_item" do
        UserSavedMenuItem.stub(:new).with({'these' => 'params'}) { mock_user_saved_menu_item(:save => false) }
        post :create, :user_saved_menu_item => {'these' => 'params'}
        assigns(:user_saved_menu_item).should be(mock_user_saved_menu_item)
      end

      it "re-renders the 'new' template" do
        UserSavedMenuItem.stub(:new) { mock_user_saved_menu_item(:save => false) }
        post :create, :user_saved_menu_item => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_saved_menu_item" do
        UserSavedMenuItem.stub(:find).with("37") { mock_user_saved_menu_item }
        mock_user_saved_menu_item.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :user_saved_menu_item => {'these' => 'params'}
      end

      it "assigns the requested user_saved_menu_item as @user_saved_menu_item" do
        UserSavedMenuItem.stub(:find) { mock_user_saved_menu_item(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:user_saved_menu_item).should be(mock_user_saved_menu_item)
      end

      it "redirects to the user_saved_menu_item" do
        UserSavedMenuItem.stub(:find) { mock_user_saved_menu_item(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(user_saved_menu_item_url(mock_user_saved_menu_item))
      end
    end

    describe "with invalid params" do
      it "assigns the user_saved_menu_item as @user_saved_menu_item" do
        UserSavedMenuItem.stub(:find) { mock_user_saved_menu_item(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:user_saved_menu_item).should be(mock_user_saved_menu_item)
      end

      it "re-renders the 'edit' template" do
        UserSavedMenuItem.stub(:find) { mock_user_saved_menu_item(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_saved_menu_item" do
      UserSavedMenuItem.stub(:find).with("37") { mock_user_saved_menu_item }
      mock_user_saved_menu_item.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the user_saved_menu_items list" do
      UserSavedMenuItem.stub(:find) { mock_user_saved_menu_item }
      delete :destroy, :id => "1"
      response.should redirect_to(user_saved_menu_items_url)
    end
  end

end
