require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserVoteCitiesController do

  # This should return the minimal set of attributes required to create a valid
  # UserVoteCity. As you add validations to UserVoteCity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all user_vote_cities as @user_vote_cities" do
      user_vote_city = UserVoteCity.create! valid_attributes
      get :index
      assigns(:user_vote_cities).should eq([user_vote_city])
    end
  end

  describe "GET show" do
    it "assigns the requested user_vote_city as @user_vote_city" do
      user_vote_city = UserVoteCity.create! valid_attributes
      get :show, :id => user_vote_city.id.to_s
      assigns(:user_vote_city).should eq(user_vote_city)
    end
  end

  describe "GET new" do
    it "assigns a new user_vote_city as @user_vote_city" do
      get :new
      assigns(:user_vote_city).should be_a_new(UserVoteCity)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_vote_city as @user_vote_city" do
      user_vote_city = UserVoteCity.create! valid_attributes
      get :edit, :id => user_vote_city.id.to_s
      assigns(:user_vote_city).should eq(user_vote_city)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserVoteCity" do
        expect {
          post :create, :user_vote_city => valid_attributes
        }.to change(UserVoteCity, :count).by(1)
      end

      it "assigns a newly created user_vote_city as @user_vote_city" do
        post :create, :user_vote_city => valid_attributes
        assigns(:user_vote_city).should be_a(UserVoteCity)
        assigns(:user_vote_city).should be_persisted
      end

      it "redirects to the created user_vote_city" do
        post :create, :user_vote_city => valid_attributes
        response.should redirect_to(UserVoteCity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_vote_city as @user_vote_city" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserVoteCity.any_instance.stub(:save).and_return(false)
        post :create, :user_vote_city => {}
        assigns(:user_vote_city).should be_a_new(UserVoteCity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserVoteCity.any_instance.stub(:save).and_return(false)
        post :create, :user_vote_city => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_vote_city" do
        user_vote_city = UserVoteCity.create! valid_attributes
        # Assuming there are no other user_vote_cities in the database, this
        # specifies that the UserVoteCity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserVoteCity.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => user_vote_city.id, :user_vote_city => {'these' => 'params'}
      end

      it "assigns the requested user_vote_city as @user_vote_city" do
        user_vote_city = UserVoteCity.create! valid_attributes
        put :update, :id => user_vote_city.id, :user_vote_city => valid_attributes
        assigns(:user_vote_city).should eq(user_vote_city)
      end

      it "redirects to the user_vote_city" do
        user_vote_city = UserVoteCity.create! valid_attributes
        put :update, :id => user_vote_city.id, :user_vote_city => valid_attributes
        response.should redirect_to(user_vote_city)
      end
    end

    describe "with invalid params" do
      it "assigns the user_vote_city as @user_vote_city" do
        user_vote_city = UserVoteCity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserVoteCity.any_instance.stub(:save).and_return(false)
        put :update, :id => user_vote_city.id.to_s, :user_vote_city => {}
        assigns(:user_vote_city).should eq(user_vote_city)
      end

      it "re-renders the 'edit' template" do
        user_vote_city = UserVoteCity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserVoteCity.any_instance.stub(:save).and_return(false)
        put :update, :id => user_vote_city.id.to_s, :user_vote_city => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_vote_city" do
      user_vote_city = UserVoteCity.create! valid_attributes
      expect {
        delete :destroy, :id => user_vote_city.id.to_s
      }.to change(UserVoteCity, :count).by(-1)
    end

    it "redirects to the user_vote_cities list" do
      user_vote_city = UserVoteCity.create! valid_attributes
      delete :destroy, :id => user_vote_city.id.to_s
      response.should redirect_to(user_vote_cities_url)
    end
  end

end
